# Generated by Django 4.1 on 2022-09-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
